{{- range $name,$repo := .Values.repositories }}
apiVersion: v1
data:
  insecure: {{ $repo.insecure | default false | toString | b64enc }}
  type: {{ $repo.type | default "git" | b64enc }}
  url: {{ $repo.repoURL | b64enc }}
  {{- if $repo.credentials }}
  username: {{ $repo.credentials.username | b64enc }}
  password: {{ $repo.credentials.password | b64enc }}
  {{- end }}
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
    {{- toYaml $.Values.labels | nindent 4 }}
  name: repo-{{ $name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
---
{{- end }}